### PR TITLE
702 nav menu

### PR DESCRIPTION
**Pull request by lschatzkin**
The problem here is that the nav drop down is a modal, so that the user can click anywhere to close. This means it is a child of the entire screen, so aligning it with a the hamburger at all widths isn't really possible without js.  I've added a few things to make it align a little better.

### CODE REVIEW

**Comment by esoterik** [comment]
oh i just merged into master -- can you switch the branch?

**Comment by lschatzkin** [comment]
to master?

**Comment by esoterik** [comment]
yup!

**Comment by lschatzkin** [comment]
done!

**Pull request merged**
