### PR TITLE
apply CSS for privacy notice refs #118

### PR DESCRIPTION
**Pull request by mfb**

### CODE REVIEW

**Comment by mfb** [comment]
Someone should take a look at the styling here

**Comment by squiggy** [comment]
It needs more space above the blue text. It is covering the checkbox for "Don't add my name or city to this petition (we'll only list your country)." 

I pushed an edit for this in feature/privacy-notice_squiggy

**Comment by squiggy** [comment]
I cleaned up my commit and force pushed to feature/privacy-notice_squiggy

**Comment by mfb** [comment]
@squiggy you added 6px top margin to all the sections of the email tool.   Personally I think it looks better the way it was before (top margin 0).  But I don't want to bike shed...

**Comment by squiggy** [comment]
That makes sense. Actually the issue I noticed is pretty minor. The text overlaps the checkbox slightly when logged in while using Firefox. It looks fine in Chrome. 
screenshot

**Comment by mfb** [comment]
ok yeah that looks bad enough to fix, I would say.

**Pull request merged**
