### PR TITLE
Use phantomjs

### LINKED ISSUE #162: Migrate from capybara-webkit to phantom-js or similar
faster tests, fewer dependencies, fewer heads

### PR DESCRIPTION
**Pull request by wioux**
This branch switches cucumber tests to run on phantomjs instead of webkit. Fixes #162.

### CODE REVIEW

**Comment by wioux** [comment]
First build failed a feature test on travis-ci. Hitting rebuild fixed it. Tests pass locally... Something to watch out for.

**Comment by vbrown608** [comment]
This looks good! Thanks for removing packaged dependencies from the dockerfile :)

Any idea about the source of this strange new cucumber output from features/users/create_content.feature:11?
```
t
th
thi
this
this 
this i
this is
this is 
this is a
this is an
this is an 
this is an i
this is an im
this is an imp
this is an impo
this is an impor
this is an import
this is an importa
this is an importan
this is an important
this is an important 
this is an important c
this is an important ca
this is an important cal
this is an important call
```

**Comment by wioux** [comment]
Looks like capybara-webkit does not display console.log while poltergeist sends it to stdout. These messages were from [admin.js](https://github.com/EFForg/action-center-platform/blob/master/app/assets/javascripts/admin.js#L88).

**Comment by vbrown608** [comment]
:ghost:

**Pull request merged**
