### PR TITLE
Add partners to email actions, post email action form directly to tools controller, show a random partner

### PR DESCRIPTION
**Pull request by vbrown608**
- Makes email actions work a bit more like other actions:
  - Email actions are now a form that posts to /tools/email (rather than using javascript to GET tools/email_target and trigger a form submission to the submissions controller)
  - The old email email controller was unused, I merged it with email_target
- Shows users a random partner signup on the client side so the partner choice isn't cached
- Overrides the CiviCRM::post method in tests so that submissions to civi are stored in memory rather than posted and tests those submissions
- Removes commented out and dead code for launching Yahoo mail :skull: 
- Removes the email icon from email tools, closing #323

### CODE REVIEW

**Comment by wioux** [comment]
When you are logged in and there are no signup options (no partners), you still get asked for your email address:

email-action-logged-in-email-prompt

**Comment by wioux** [comment]
There is an error when you leave `Email (optional)` blank but check yes for mailings. Email could dynamically become/unbecome required when you change the radio state?

**Comment by vbrown608** [comment]
Good idea.

**Comment by wioux** [comment]
:+1: good to go

**Pull request merged**
