### PR TITLE
613 main page fixes

### LINKED ISSUE #613: Main page style fixes
Some style fixes from Hugh for the Main page of the Action Center:
1. Close space above tag line by 50%
2.  For the main featured article, align category & title with top of image
3. Take action text on button should be on 1 line
4. Reduce width of margins between columns by 1/3 (this might be hard, OK if not possible)
5. Reduce space above “See All Our Campaigns” by 50%

6. Main page: Left margin is inconsistent as window reduces 
— sometimes the left edge touches the edge of the window. 
— On tablet view, the logo and image do not align.

### PR DESCRIPTION
**Pull request by lschatzkin**
closes #613

### CODE REVIEW

**Comment by esoterik** [comment]
I'm seeing some alignment/size issues at tablet sizes:

(768 x 1024 / vertical ipad below)
image 
image

The text should be full width and the take action button needs a little more space between it and the text. The text could be bigger for the other 3 actions, and I think it'd be nice to center the images on the page.

(1024 x 768 / horizontal ipad below
Screenshot_2019-08-15 EFF Action Center

This looks fine except for the same space issue with the button.

lgtm at all other sizes!!

**Comment by lschatzkin** [comment]
I cannot duplicate your screen shot for: (768 x 1024 / vertical ipad below), perhaps you can show me?

**Comment by esoterik** [comment]
I just checked and weirdly it only happens when I set "iPad" size in firefox, not when i manually decrease the window size in responsive mode...maybe it doesn't matter?

**Comment by lschatzkin** [comment]
That's where I'm looking too. I'm going to check on Browserstack.

**Comment by lschatzkin** [comment]
Okay, weirdly this only showed for me at widths 720px-730px!

**Comment by esoterik** [comment]
i'm still seeing the issue with the featured action text not being full width, but given that it only happens under extremely odd circumstances and looks fine when i manually resize to sizes in the issue range, I'm going to merge

**Pull request merged**
