### PR TITLE
Allow users to contact select congress members

### PR DESCRIPTION
**Pull request by esoterik**
WIP

### CODE REVIEW

**Comment by lschatzkin** [comment]
Okay, I'm not sure what I should be seeing so far, but this is what I see.  The congress people's names show up, the checkboxes are currently hidden (as expected). When I show the checkboxes I don't see them having any effect. I'm not sure if this is the part you'd like me to do?
Screenshot from 2019-09-11 08-55-40
Screenshot from 2019-09-11 08-55-57

**Comment by esoterik** [comment]
I'll handle the JS that shows & hides the subsequent forms when the checkboxes change. It works on the backend right now. I was hoping for some help with the styling of the checkboxes!

**Comment by esoterik** [comment]
the JS has been added!

**Comment by lschatzkin** [comment]
I'm going to add myself a ticket to try to improve the look of these checkbox in the future, but for now they are minimally styled.

**Pull request merged**
