### PR TITLE
Fix petition thank yous

### PR DESCRIPTION
**Pull request by esoterik**
Also hides the "Learn more" toggle when there isn't a description set, and centers the thank you title below the image.

### CODE REVIEW

**Comment by lschatzkin** [comment]
I'm getting an error message on the form that says "Something seems to have gone wrong. Please try again." No errors showing on rails server.

**Comment by esoterik** [comment]
hmm. I disabled thank you emails in my sandbox again for testing this one, could that be it?

**Comment by lschatzkin** [comment]
Tell me again how to disable the emails

**Comment by esoterik** [comment]
in the tools controller:
```diff
-  after_action :deliver_thanks_message, only: [:email, :call, :petition, :message_congress]
-  skip_after_action :deliver_thanks_message, if: :signature_has_errors
+  # after_action :deliver_thanks_message, only: [:email, :call, :petition, :message_congress]
+  # skip_after_action :deliver_thanks_message, if: :signature_has_errors
```

in concerns/tooling:
```diff
   def deliver_thanks_message
-    @email ||= current_user.try(:email) || params[:email] || params.dig(:subscription, :email)
-    if @email.present?
-      UserMailer.thanks_message(@email, @action_page, user: @user, name: @name).deliver_now
-    end
+    # @email ||= current_user.try(:email) || params[:email] || params.dig(:subscription, :email)
+    # if @email.present?
+    #   UserMailer.thanks_message(@email, @action_page, user: @user, name: @name).deliver_now
+    # end
   end
 end
```

**Comment by lschatzkin** [comment]
Yep, that solved the error problem.

**Pull request merged**
