### PR TITLE
Petition signature deletion

### PR DESCRIPTION
**Pull request by wioux**
This branch adds a search feature to the page on `/admin/petitions/:id` so that signatures with a particular name or email can be listed. The search is case insensitive and allows for partial matches. It also provides a button on that page for deleting signatures, fixing #188.

### CODE REVIEW

**Comment by vbrown608** [comment]
This looks good! Thanks for removing packaged dependencies from the dockerfile :)

Any idea about the source of this strange new cucumber output from features/users/create_content.feature:11?
```
t
th
thi
this
this 
this i
this is
this is 
this is a
this is an
this is an 
this is an i
this is an im
this is an imp
this is an impo
this is an impor
this is an import
this is an importa
this is an importan
this is an important
this is an important 
this is an important c
this is an important ca
this is an important cal
this is an important call
```

**Comment by vbrown608** [comment]
Filtering works great! 

I recommend adding a few css classes for visual consistency with the rest of the site:
- btn-danger (rather than btn-cancel and btn-default) class on the "Destroy" button to match other delete buttons on the site
- btn, btn-sm, and btn-default classes on the "Search" button
- form-control and input-sm class on the search field

The function of the "select all" box wasn't obvious to me. We'll also need to make it clear to users whether they're selecting all the signatures for the petition, just the ones that match the current filter, or just the ones that match the filter and are visible on the current page. Happy to do some co-planning on that if you want.

Last thing - I suspect that the check boxes will need either a label or a column header to make them accessible to users with screen readers. I think a visually hidden label element that says something like "select for deletion" would work well. I'm not sure if bootstrap provides a good class for that, the action center already has one, or we'd need to create our own (something like http://www.zeldman.com/2012/03/01/replacing-the-9999px-hack-new-image-replacement/)

**Comment by vbrown608** [comment]
I did some more reading about accessibility for checkboxes in tables last night. Made a tiny tweak to match the 508 docs: http://www.section508.va.gov/support/webdev/2_7a.asp

I also realized a visually-hidden label might be helpful for the search bar. Bootstrap 3 provides the sr-only (screen reader only) class for that.

I think this is ready for merge now!

**Comment by wioux** [comment]
:+1: including the signature name in the select title is a nice touch.

**Pull request merged**
