### PR TITLE
Add new thank you flow for actions

### LINKED ISSUE #502: Add illustration to thank you page

### PR DESCRIPTION
**Pull request by esoterik**
Closes #502, #504, and #505

The thank you section is pretty much unstyled at the moment. It also is not tested for congress message actions -- I kept getting a CORS error after entering an address and hitting "Find your reps".

There are some new test failures in this PR but I'll handle them in the big fix-all-the-tests branch that I've been working on. As far as I can tell, the new failures are entirely a result of visual changes, not any actual functionality breaking.

### CODE REVIEW

**Comment by lschatzkin** [comment]
This is great.
For the petitions, I'm seeing both the Signed section and the Thank you section. Is that correct, and I need to fix the Signed section, or should only the Thank you appear?
signed
Also, I never seem to get to a Thank You page for the Call Tool, not sure if that's correct.

**Comment by esoterik** [comment]
okay, changed the behavior for call and petition actions!

**Comment by lschatzkin** [comment]
Now that I'm looking at it again, I think we should have the thank you appear at the bottom of the tweet action as well, since that is the last screen the user sees. Sorry I didn't notice this sooner.
tweet action

**Comment by esoterik** [comment]
hmm, for me twitter opens in a new, small window and the action center stays visible. It seems potentially confusing to show the "thank you" section before the user does anything

**Comment by lschatzkin** [comment]
Okay, let's leave it as is. Merging!

**Pull request merged**
