### PR TITLE
Upgrade to paperclip 5.2

### PR DESCRIPTION
**Pull request by k-stewart**

### CODE REVIEW

**Comment by vbrown608** [comment]
I'm able to upload a photo successfully, however when I select it and save the action I see 
```
Paperclip::AdapterRegistry::NoHandlerError - No handler found for "https://actioncenter.s3-us-west-1.amazonaws.com/uploads/de000a90e52b4404bfd4be6f18528cca/test.png"
```

**Comment by k-stewart** [comment]
I get a 403 on this branch and master both.  I think i have bad s3 credentials; will have to get them from you or someone tomorrow.

**Comment by k-stewart** [comment]
Upload and save both work! 🌮

**Comment by vbrown608** [comment]
Save works for me now, but the saved image 404s (ie on the edit page after save or on the action itself)

**Comment by vbrown608** [comment]
Looks good!

(Please ignore previous comment - it was an issue with my sandbox)

**Pull request merged**
