### PR TITLE
Set Vary: Accept-Encoding, Accept-Language, Cookie

### PR DESCRIPTION
**Pull request by wioux**
Set Vary HTTP header and include Accept-Language.

### CODE REVIEW

**Comment by mfb** [comment]
hrm this sounds bad for cacheability. do we actually vary language based on the Accept-Language header?  I'd prefer to change the URL when serving content in a different language.

**Comment by wioux** [comment]
We [set locale](https://github.com/EFForg/action-center-platform/blob/master/app/controllers/application_controller.rb#L64) based on the Accept-Language header. This creates a bug at the moment where if you're the "first" visitor to a page, everyone thereafter sees the page in the locale that was rendered for you (until the cached page expires).

**Comment by mfb** [comment]
lol yes that would.

ok well maybe we can revisit this in future: would be nice to improve cacheability and allow people to share URLs in specific languages by altering the URL per-language.

**Comment by vbrown608** [comment]
:cookie:

**Pull request merged**
