### PR TITLE
fixed privacy notice on non-congress form pages

### PR DESCRIPTION
**Pull request by lschatzkin**

### CODE REVIEW

**Comment by esoterik** [comment]
i think this is missing some JS for the tooltips, they're still just shown for me:
image

**Comment by lschatzkin** [comment]
> i think this is missing some JS for the tooltips, they're still just shown for me:
> image

Weird! It's CSS only. I'll see if I can replicate.

**Comment by lschatzkin** [comment]
I tried merging the latest merge-redesigns into the branch, but still am not seeing the brokenness.

**Comment by esoterik** [comment]
it looks fine for me now!

**Pull request merged**
